name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build with MSBuild
      run: msbuild /p:Configuration=Release your_project.sln

    - name: Upload exe
      uses: actions/upload-artifact@v3
      with:
        name: mpc-hcc
        path: ./build/Release/your_executable.exe
