name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up CMake
      uses: actions/setup-cmake@v1
    - name: Configure
      run: cmake .
    - name: Build
      run: cmake --build .
    - name: Upload exe
      uses: actions/upload-artifact@v2
      with:
        name: mpc-hcc
        path: ./build/your_executable.exe
